# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2.7.0
group=de.cristelknight.wwoo
java_version=25

# Common
minecraft_version=26.2
mod_id=wwoo

minecraft_version_range=[26.2, 26.3)
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Dependencies
jankson_version=1.2.3
cristellib_version=3.1.11

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_api_version=0.160.0+26.2
fabric_loader_version=0.19.5
fabric_loader_min_version=0.18.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.86
neoforge_version_range=[26.2,)
neoforge_loader_version_range=[4,)

# Mod Properties
mod_name=William Wythers' Overhauled Overworld
### https://creativecommons.org/licenses/by-nc-sa/4.0/
license = CC BY-NC-ND 4.0
description = In this mod I seek to re-create the vanilla biomes in a way that makes a more realistic and atmospheric world.
homepage = https://modrinth.com/mod/wwoo
discord = https://discord.gg/G2UJ2FAuYh
mod_author = Cristelknight

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
