pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        def fabricRepository = maven {
            name = 'Fabric'
            url = uri('https://maven.fabricmc.net')
        }
        exclusiveContent {
            forRepository{fabricRepository}
            filter {
                includeGroupAndSubgroups('net.fabricmc')
            }
        }
        maven { url = "https://maven.firstdark.dev/releases" }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'WWOO'
includeBuild('build-logic')
include('common')
include('fabric')
include('neoforge')
